### ISSUE TITLE
[BUG] Campus Guide Highlights should be auto added to their Favorites widget

### ISSUE THREAD

**Issue by joegrohens** [rokwire/illinois-app#3032]
**Describe the bug**
When a Campus Guide article is promoted as a "Highlight", it should be listed automatically in two places:

1. _Browse > Campus Guide >  Campus Guide Highlights_
2. _Favorites > Campus Guide Highlights._

At this writing there are four items in _Browse > Campus Guide >  Campus Guide Highlights_:

![browse highlights list copy](https://user-images.githubusercontent.com/66988329/225135988-47da55c4-4749-476d-adb9-0bd51e3e20e0.jpeg)

None of these items appears in _Favorites > Campus Guide Highlights_:

![highlights widget copy](https://user-images.githubusercontent.com/66988329/225136357-5dcfa9de-c7a0-4ecb-83d5-290bc58c233b.jpg)

**What should be done**

1. The Favorites Widget for Campus Guide Highlights should be populated automatically with ALL items that have the appropriate promotion interval, user role, and i-card value for the particular user. (In other words, if an item appears in _Browse > Campus Guide >  Campus Guide Highlights_, it should also appear in the favorites widget.

2. The wording in the screen of the Favorites widget for Campus Guide Highlights should be changed. When there are no items to display in the favorites widget for Campus Guide Highlights, it should display the following text: Promoted content from Campus Guide will appear here automatically.

**Comment by mihail-varbanov** [comment]
This should be resolved in version 4.3.40.

**Comment by joegrohens** [comment]
The Campus Guide Highlights do not appear in the favorites widget in 4.3.43 dev. 

![campus guide highlights copy](https://user-images.githubusercontent.com/66988329/233200422-4e23f20b-3668-4b8c-a106-9f41e53432f6.png)

**Comment by joegrohens** [comment]
The Campus Guide Highlights also do not appear in the favorites widget in 4.3.46 dev.

![campusguidehighlights](https://user-images.githubusercontent.com/66988329/234061530-846cdfbe-36d2-4404-9329-2d7847c8fd36.png)

**Comment by joegrohens** [comment]
This issue is still unresolved in v4.3.47 dev

![campus guide highlights](https://user-images.githubusercontent.com/66988329/234156649-16986cea-6ac1-4e44-ac66-335b45b54989.png)

**Comment by mihail-varbanov** [comment]
Hi @joegrohens,

I hope you understand that Campus Guide Highlights widget in Favorites panel displays guide article that are:
1. Promotion, that is currently active;
2. Marked as favorite.

Currently I see just one active promoted item labeled "Illinois App Service Status Webpage". However it is not marked to be set as favorite by default. I mentioned earlier above "Please note that the guide entry should be marked as favorite by default (content_type_favorite =true).".

I just checked the situation in the Admin app and noticed that it does not enable the Favorite checkbox for promoted items. Dobromir will fix this today and it will get available in the admin app version 4.1.19. Once you mark "Illinois App Service Status Webpage" as Favorite in the admin app you should see it in the Campus Guide Highlights widget in the Favorites panel.

**Comment by joegrohens** [comment]
PS - Should I re-assign this to you for you to see my new comment?

**Comment by mihail-varbanov** [comment]
Hi @joegrohens,

It is a good practice to assign the issue to us when you expect some action or even answer. GIT notifies us for all comments in the issues that we are involved in but this is often dropped in the sea of notifications. Also, please keep in mind that we are often busy with development of new features and cannot respond in time to all GIT comments.

1. It is normal for the update to take some time. In general, in the dev environment, sending the application to the background and then activating it back after 2 minutes should make the update visible. In the production environment this time interval is 3 hours.

2. The only way to make an item favorite by default, i.e. without the user doing this explicitly, is to turn on the Favorite checkbox in the Admin app. I just checked the admin app and noticed that the Favorite checkbox is visible for promoted items but the taps on it are ignored. I will let @dobromirdobrev know about this to fix it.

**Comment by mihail-varbanov** [comment]
Update: we just updated the admin app so the fix for Favorite checkbox should get available in the next build for version 4.1.20

**Comment by joegrohens** [comment]
Thank you, @mihail-varbanov

**Comment by mihail-varbanov** [comment]
You are welcome, @joegrohens.

I forgot to mention that the quickest way to acknowledge guide content updates in the client app is to restart it by first killing the app and then launching it again.
