### ISSUE TITLE
[BUG] Krannert Performance Center Events, entered in Webtools, are not displayed [ver. 5.0.62]

### ISSUE THREAD

**Issue by knguyenjahiel** [rokwire/illinois-app#3711]
**Describe the bug**
Performances, concerts, events at the Krannert Performance Center, entered in Webtools, are not displayed in the app [ver. 5.0.62]. All Krannert Center events are properly listed in ver. 4.3.61.

**To Reproduce**
1. In 5.0.62 dev, touch All Events
2. Search "Ellnora". Only one event (Yamandu Costa | ELLNORA THE GUITAR FESTIVAL) displays even though the Festival has several events from 9/8-9/9. Please see Fig. 1
3. Krannert Performance Center has multiple events scheduled throughout the semester.
4. In 4.3.61 prod, touch Suggested Events
5. Search "Ellnora". You will see 3 events listed. Please see Fig. 2

**Expected behavior**
All Krannert Performance Center events should be listed in the app.

**Screenshots**
Fig. 1. Ver 5.0.62 dev fail to list all Krannert Performance Center events
![Events Listed 5 0 62](https://github.com/rokwire/illinois-app/assets/118769169/8280938f-98d3-4919-a0f1-5786de0cf20d)

Fig. 2. Ver 4.3.61 prod properly listing all Krannert Performance Center events. You need to scroll down to see all listed Ellnora event
![Events Listed 4 3 61](https://github.com/rokwire/illinois-app/assets/118769169/adc40b6f-4b07-42cf-868b-44e35324d870)

**Smartphone (please complete the following information):**
 - Device: Pixel 6; Android 13
 - Version: IL app 5.0.62 dev

- Device: iPhone SE, 2nd Gen
 - Version: IL app 4.3.61 prod

**Comment by sandeep-ps** [comment]
This seems connected to the data import from Events BB to Calendar BB. I have opened an issue in Calendar BB with more details and linked it here.

**Comment by sandeep-ps** [comment]
Hi, @knguyenjahiel, Since the event mentioned in the bug report expired, I tested this with another Kranner event ("Krannert Center Uncorked with The B-Sides"). Previously, it did not appear in the Calendar BB. It's appearing now. The root cause is fixed in the Calendar BB as per Petyo's comment on the linked issue. I can see that it's showing up in the Illinois app Dev build (I currently have 5.0.55, but it should show up in other Dev builds, too). It might not appear in the PROD build yet, but it should very soon after the latest Events Manager/Events BB is deployed to PROD (request in progress). 

Please review and close this issue if you agree that it's resolved. If you find other missing events, please share them here or create a new bug report. Thanks.

CC: @bingzhang, @minump

**Comment by knguyenjahiel** [comment]
Based on Sandeep's comment about Krannert events showing in Dev builds, I have tested 5.0.62 Dev version, and the app is still not displaying _all_ events. Only 3 events are listed, no filter applied (screen capture below). Their website shows at least 20 events from today (9/14) to the end of September (https://krannertcenter.com/calendar/print).

Today, 4.3.61 Prod is only displaying 1 event for the rest of September. Search based on event title (e.g., Pygmalian, September 21) results in "No results found."

@sandeep-ps

**Comment by bingzhang** [comment]
@knguyenjahiel I want to share one piece of information, the calendar events are from the webtools https://publicaffairs.illinois.edu/services/webtools/. I suspect not all events from https://krannertcenter.com/calendar/print will be imported. 

I just test on 4.3.61 app, I searched the keyword of Krannert, and there are 6 found.

**Comment by vburgett** [comment]
That is correct, @bingzhang. Not all events on krannertcenter.com have been entered into Webtools. It looks like they have published 5 events to Webtools that should be showing up in the app. https://calendars.illinois.edu/list/33 

(Please note that Krannert Center is different than Krannert Art Museum—two different places and teams, two different webtools calendars, two different sets of events.)

**Comment by bingzhang** [comment]
@vburgett Thanks for your information.

I did test on 4.3.61 and 5.0.62 apps. I can search and find those events.

**Comment by knguyenjahiel** [comment]
@vburgett, thanks for your information: events entered in Webtools (https://calendars.illinois.edu/list/33) are displaying. I'll learn from you other methods Krannert Performance Center is using to see if we can persuade them to use one platform (?)

@bingzhang, thank you for looking into this issue. I will close the ticket.
