### ISSUE TITLE
[BUG] WEB: image in a group post does not show up for other admins

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#4841]
When a group admin posts an image to a group via the website, the other admins do not see the post image on the website. (Everyone _does_ see the image in the app.)

**Comment by dobromirdobrev** [comment]
This is fixed in version 6.1.69 and/or 6.2.1 of the web app.

**Comment by vburgett** [comment]
Thanks, @dobromirdobrev. I will test once I have access.

**Comment by vburgett** [comment]
Confirming that this is now fixed on dev.

**Comment by vburgett** [comment]
@dobromirdobrev This still does not work on prod 7.0.5. Here are the steps:

1. As an admin, I created a post with an image on the web in the group "New Student Experiences: First-Year Students"  
2. Another group admin went to look at the post on the web as well. He could NOT see the image.
3. I went back to the post, and my post was there but the image was gone.
4. The other group admin looked at the post again on the web. Still no image.
5. I went back again to my post and the image was once again gone. 

![Image](https://github.com/user-attachments/assets/f28963ad-5147-41a5-9d8c-1991c810abca)

**Comment by dobromirdobrev** [comment]
@vburgett ,

Is there any specifics of how to reproduce this problem?

Since I'm now a member of this group, I do see the images in the web app on production version 7.0.5

Please see the screenshots:

![Image](https://github.com/user-attachments/assets/0e86d752-c752-4613-844a-552bee67fdcb)
![Image](https://github.com/user-attachments/assets/739db30f-36ac-4254-bdc9-bc471da701a9)

Which browser do you use?
Could you please double-check and see if the pictures are visible?
Any other information would be helpful.

Thanks!

**Comment by vburgett** [comment]
Closing this ticket since it is a repeat of #5029
