### ISSUE TITLE
[USABILITY] Display Group Admin-Only Tabs Last

### ISSUE THREAD

**Issue by vburgett** [rokwire/illinois-app#5052]
On prod, a Group's tabs display in the order outlined under Group Admin Settings > Group Content with the admin tab "Scheduled" displaying at the end of tabs. (See screenshot.)

Can this work the same way on dev with the two admin tabs "Scheduled" and "Past Events" displaying AFTER the other group modules? 

![Image](https://github.com/user-attachments/assets/e13b9cd3-5b4b-4e17-81ce-32be7a2c8644)

![Image](https://github.com/user-attachments/assets/84d5ceba-ec3a-49f5-b5d8-fd87ddfd7dc5)

**Comment by vburgett** [comment]
This issue was addressed via #5022.

**Comment by mihail-varbanov** [comment]
I hope the tabs order be fixed in version 7.0.18.

**Comment by vburgett** [comment]
@mihail-varbanov now I am seeing two instances of the "Scheduled" tab—one that is in the correct order and one that is still in the wrong place. This is dev v7.0.18.

![Image](https://github.com/user-attachments/assets/1463fe9e-2545-4913-95de-e37467495361)

**Comment by mihail-varbanov** [comment]
Тhis happened because this particular group has messed up data. It seems there was a time when Scheduled was part of Group Advanced Content Settings, and it still persists there as a display tab. The regular groups on production should not have this problem. Anyways, I took care to handle this case as well, in version 7.0.20.

**Comment by vburgett** [comment]
This now works on dev and prod for the web and the mobile app v7.0.20. Thank you, @mihail-varbanov
